### ISSUE TITLE
Getting Involved

### ISSUE THREAD

**Issue by jcooper67** [3l-Sabio/OpenSTRAN#1]
I notice you labeled this project as open source and I was interested in getting involved. What's the best way to do that?

For some context :

I'm a structural engineer by trade who's pursuing their masters in computer science ( I hold a bachelor and masters in Structural Engineering as well). I initially started programming because I was interested in developing my own analysis software.

I'm mainly proficient in Java and Python and have experience with Tkinter and the other libraries you're utilizing.

Thanks!

**Comment by 3l-Sabio** [comment]
@jcooper67 ,

Thank you for reaching out. It seems we share similar backgrounds; I'm intrigued to learn more about your experiences in structural engineering and your interest in software development. If you have the time, your voluntary contributions to the project would be greatly appreciated.

In response to your inquiry, I've added some general suggestions on how to start contributing to the project in the `README.md` file under the _"Get Involved"_ section. Please review these suggestions and feel free to begin contributing in any capacity you prefer.

Given your mention of Tkinter, it's evident that you've delved into the code. Are you interested in developing the graphical user interface aspect? Presently, the project is in dire need of documentation and validation testing. Please let me know if any of these areas pique your interest.

**Comment by jcooper67** [comment]
@3l-Sabio 

I've got some free time this week, I can definitely start to look at developing the user interface at some point. I can begin with documentation and testing if that's more pressing though.
